"""WS-D: the DESIGN.md audit wiring (WAVE2 A1).

DESIGN.md + DESIGN_MANIFEST.json are NUTS-derived and NOT byte-diffed; `generate_design.py --audit`
tolerance-checks them. Here we (a) pin the audit tolerances against a SILENT softening (the WAVE1 1.5
never-soften rule; same guard as test_calibration_audit.py), and (b) verify the doc<->manifest render
deterministically, carry the mandated verbatim paragraphs, and pass `provenance --check` -- all WITHOUT
running the NUTS pipeline (a fixed synthetic ``res`` exercises the pure rendering path).
"""

import importlib.util
from pathlib import Path

import openmucf
from openmucf import design
from openmucf.provenance import check_manifest, write_manifest

_SCRIPT = Path(openmucf.__file__).resolve().parent.parent / "scripts" / "generate_design.py"


def _load_script():
    """Import the generator by path (no NUTS: all work is guarded behind main())."""
    spec = importlib.util.spec_from_file_location("_gen_design", _SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _mock_res():
    """A fixed synthetic result matching compute()'s structure -- no NUTS, fully deterministic."""
    cand_ids = ["C1", "C2", "C3", "C4"]
    eig_bits = {"C1": 1.629, "C2": 1.782, "C3": 1.081, "C4": 3.240}
    ose = {"C1": 0.231, "C2": 0.049, "C3": 0.560, "C4": -0.026}
    rc = {"C1": 0.070, "C2": 0.017, "C3": 0.101, "C4": 0.408}
    ri = {"C1": 0.002, "C2": 0.017, "C3": 0.103, "C4": 0.408}
    return {
        "seed": 0,
        "registry": design.registry(42.95, 15.0),
        "cand_ids": cand_ids,
        "eig": {c: {"eig_bits": eig_bits[c], "n_outer": 256, "n_inner": 256} for c in cand_ids},
        "eig_c3_inflated": {"eig_bits": 2.492},
        "sdc": {c: {"ose_contraction": ose[c], "n_synth": 8,
                    "R_contraction": {"constant": rc[c], "inflated": ri[c]}} for c in cand_ids},
        "zero_eig_bits": -1e-7,  # exercises the negative-zero normalisation
        "sobol": {"top_param": "R"},
        "settings": {"n_outer": 256, "n_inner": 256, "n_synth": 8,
                     "num_warmup": 1000, "num_samples": 4000},
    }


def test_audit_tolerances_pinned():
    """Any SILENT softening of the audit tolerances trips this test (same literal-substring guard as
    test_calibration_audit.py). EIG at 5% relative (WAVE2 A1); contraction at 3 pp absolute. Changing
    either requires deliberately editing this pin + a dated planning-model amendment (WAVE1 1.5)."""
    src = _SCRIPT.read_text(encoding="utf-8")
    assert "AUDIT_RTOL_EIG = 0.05" in src
    assert "AUDIT_ATOL_CONTRACTION = 0.03" in src


def test_design_doc_and_manifest_render_deterministically(tmp_path):
    """The doc + manifest render bit-identically from a fixed result, carry the verbatim paragraphs +
    the I6 fence, and every tracked manifest number is found in the doc (provenance green)."""
    mod = _load_script()
    res = _mock_res()
    h1, _ = mod.build_headline(res)
    h2, _ = mod.build_headline(res)
    md1 = mod.build_markdown(h1, res)
    md2 = mod.build_markdown(h2, res)
    assert md1 == md2  # deterministic given the result

    # verbatim estimand-discipline paragraph (WAVE2 6.1)
    assert "EIG on omega_s^eff at stated conditions is well-posed" in md1
    assert "generated by the ASSUMED structural form R(phi)" in md1
    assert "report the class-flip as a finding" in md1
    # verbatim scenario-B disclaimer
    assert "the scenario-B MuFusE EIG is large BY CONSTRUCTION (the widest prior wins)" in md1
    assert "this is a property of the prior, not of the experiment." in md1
    # I6 fence in the header (generic warm-thread language; no named private outreach targets in a public doc)
    assert "never cold-mailed" in md1 and "ALREADY-WARM thread" in md1 and "not outreach" in md1
    assert "Antognini" not in md1 and "NCCR" not in md1  # public-hygiene: no private outreach target names
    # negative-zero normalised, class-flip + C4 conditional surfaced
    assert "yields EIG =\n" in md1 or "yields EIG = " in md1
    assert "-0.000" not in md1
    assert "class-flip finding (YES)" in md1.lower() or "Class-flip finding (YES)" in md1
    assert "C4 (X-ray/neutron ratio) is **included**" in md1

    # write doc + manifest to a temp repo root; provenance must find every tracked value in the doc
    (tmp_path / "DESIGN.md").write_text(md1, encoding="utf-8")
    entries = mod.build_manifest_entries(h1, res["cand_ids"])
    write_manifest(tmp_path / "DESIGN_MANIFEST.json", entries, mod._manifest_inputs(),
                   generated_by="scripts/generate_design.py")
    failures = check_manifest(tmp_path / "DESIGN_MANIFEST.json", repo_root=tmp_path)
    assert failures == [], failures
    assert len(entries) >= 15  # 4x3 sd-contraction cells + 4 EIG + inflated + 2 sanity claims
