#!/usr/bin/env python3
"""Generate the ``.g4dat`` conformance corpus: one file per rejection the format defines.

``FORMAT_SPEC.md`` section 4 lists sixteen error codes and a three-phase reporting order. Prose is
not a test suite: two conforming readers can each implement that section honestly and still disagree
about which code a file with three defects in it deserves. This script turns the section into
artifacts -- one small file per code, per ordering rule and per tie-break -- and records, in
``expected.tsv``, the verdict the reference implementation gives each one.

Three disciplines, and they are the reason this exists rather than a directory of hand-written
fixtures:

* **no verdict is typed.** Every ``(code, line)`` in ``expected.tsv`` comes from
  :func:`reference_verdict`, which runs ``openmucf.g4.spec`` over the generated bytes. A fixture
  whose expected code was typed by hand tests the author's belief about the format, not the format.
* **every case is built from one template**, which is asserted conforming at import. A case is then
  exactly one edit away from a clean file, so what it exercises is the edit and nothing else.
* **the corpus is regenerated and byte-compared**, like every other generated artifact here
  (``--audit``). A fixture nobody can rebuild is a fixture nobody can trust after the first edit.

The C++ validator reads the same directory and must report the same ``(code, line)`` on every
member, which is what makes this a conformance corpus rather than a Python regression suite.
"""

from __future__ import annotations

import filecmp
import hashlib
import sys
import tempfile
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import NamedTuple

from openmucf.g4 import provenance, spec

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "tests" / "fixtures" / "g4dat_conformance"
#: The malformed-by-design fixtures that predate this corpus. They are copied in byte-for-byte
#: rather than rebuilt: their exact bytes are what three older tests assert against, and a corpus
#: that "regenerated" them would quietly become a second, divergent source of truth.
BAD_FIXTURES = ROOT / "tests" / "fixtures" / "g4dat_bad"
EXPECTED_NAME = "expected.tsv"

#: The Layer-2 stand-in for the two cases that need a sibling. Its content is irrelevant -- E009 is
#: a statement about a SHA-256 over bytes, not about JSON -- but it is JSON-shaped so that a reader
#: opening it is not misled about what a real Layer-2 file looks like.
SIBLING_BYTES = b'{\n  "conformance": true\n}\n'
_SEED = b"conformance"


def _directive(keyword: str, value: str) -> str:
    """One header line, padded exactly as :func:`spec.render` pads it."""
    return ("#" + keyword).ljust(spec._KEYWORD_WIDTH) + value


#: The one conforming file every case is derived from: ``parity`` profile (so ``#SOURCESHA`` is
#: required and E013 is reachable), four columns, three ascending records. Short on purpose -- a
#: reader who has to find the one edited line should not have to read a hundred of them.
TEMPLATE_LINES: tuple[str, ...] = (
    _directive("GRAMMAR", spec.GRAMMAR_VERSION),
    _directive("DATASET", "G4MuonicData"),
    _directive("VERSION", "0.0.0-conformance"),
    _directive("PROFILE", spec.PARITY_PROFILE),
    _directive("SEAM", spec.ALLOWED_SEAMS[0]),
    _directive("TABLE", "conformance_case"),
    _directive("GENERATOR", "openmucf-g4 conformance"),
    _directive("SOURCEDIGEST", hashlib.sha256(_SEED).hexdigest()),
    _directive("SOURCESHA", hashlib.sha1(_SEED, usedforsecurity=False).hexdigest()),
    _directive("UNITS", "value=1e6/s unc=1e6/s"),
    _directive("COLUMNS", "Z A value unc"),
    _directive("VALIDITY", "Z:listed A:listed"),
    "1 1 1.5 0.1",
    "2 3 2.5 0.2",
    "6 12 3.5 0.3",
    spec.END_MARKER,
)


# --------------------------------------------------------------------------------------------
# line surgery -- every case is one edit away from the template
# --------------------------------------------------------------------------------------------


def _encode(lines: Iterable[str]) -> bytes:
    """Join to a newline-terminated document. LF only, and ``latin-1`` so a case may plant a byte
    outside ASCII without the encoder deciding what that byte means."""
    return ("\n".join(lines) + "\n").encode("latin-1")


def _index_of(lines: list[str], keyword: str) -> int:
    """Where ``#KEYWORD`` sits, matched on the whole keyword so ``SOURCESHA`` never hits
    ``SOURCEDIGEST``."""
    marker = "#" + keyword
    for index, line in enumerate(lines):
        if line == marker or line.startswith(marker + " "):
            return index
    raise KeyError(f"the template has no '{marker}' line")


def _first_record(lines: list[str]) -> int:
    """The first line that is neither a directive nor the terminator."""
    for index, line in enumerate(lines):
        if not line.startswith("#"):
            return index
    raise KeyError("the template has no records")


def _set(lines: list[str], keyword: str, value: str) -> list[str]:
    lines[_index_of(lines, keyword)] = _directive(keyword, value)
    return lines


def _drop(lines: list[str], keyword: str) -> list[str]:
    del lines[_index_of(lines, keyword)]
    return lines


def _after(lines: list[str], keyword: str, line: str) -> list[str]:
    lines.insert(_index_of(lines, keyword) + 1, line)
    return lines


def _record(lines: list[str], offset: int, text: str) -> list[str]:
    lines[_first_record(lines) + offset] = text
    return lines


# --------------------------------------------------------------------------------------------
# the reference verdict -- the only place a (code, line) is ever produced
# --------------------------------------------------------------------------------------------


def reference_verdict(source: Path | bytes, sibling: bytes | None = None) -> tuple[str, int]:
    """What ``openmucf.g4.spec`` says about these bytes: ``(code, line)``, or ``("OK", 0)``.

    Decoded ``latin-1``, deliberately: that mapping is byte-transparent, so a byte outside the
    format's set survives into the string and is diagnosed as E005 by the format's own rule rather
    than by a ``UnicodeDecodeError`` raised before the format ever sees it. A reader that decoded
    UTF-8 here would be answering a different question.

    When ``source`` is a path, the Layer-2 sibling is looked up beside it; E009 is the one code that
    cannot be decided from the Layer-1 file alone.
    """
    if isinstance(source, Path):
        raw = source.read_bytes()
        candidate = source.with_name(source.stem + ".prov.json")
        sibling = candidate.read_bytes() if candidate.exists() else sibling
    else:
        raw = source
    try:
        table = spec.parse(raw.decode("latin-1"))
        spec.validate(table)
        if sibling is not None:
            provenance.check_source_digest(table, sibling)
    except spec.G4DatFormatError as exc:
        return exc.code, exc.line
    return "OK", 0


# The template is the baseline every case is measured against, so a template that stopped
# conforming would silently turn most of this corpus into cases about the template.
assert reference_verdict(_encode(TEMPLATE_LINES)) == ("OK", 0), (
    "the conformance template is no longer a conforming file; every case built from it is now "
    "exercising the template's defect instead of its own"
)


# --------------------------------------------------------------------------------------------
# the cases
# --------------------------------------------------------------------------------------------

#: A case's ``build`` returns the ``.g4dat`` bytes, or a ``(.g4dat, .prov.json)`` pair when the case
#: needs a Layer-2 sibling.
Build = Callable[[list[str]], bytes | tuple[bytes, bytes]]


class Case(NamedTuple):
    """One corpus member: the file's stem, and how its bytes are built from the template."""

    name: str
    build: Build


def _header_only_no_end(lines: list[str]) -> bytes:
    """Header without ``#VALIDITY``, no records, no ``#END``: the directive block never closes."""
    _drop(lines, "VALIDITY")
    return _encode(lines[: _first_record(lines)])


def _copied(name: str) -> Build:
    """A member copied byte-for-byte out of ``tests/fixtures/g4dat_bad``.

    The member keeps the fixture's own name, so the correspondence between the two directories is a
    name lookup rather than a mapping table anyone has to maintain.
    """

    def build(_lines: list[str]) -> bytes:
        return (BAD_FIXTURES / name).read_bytes()

    return build


CASES: tuple[Case, ...] = (
    # -- one per section-4 code ---------------------------------------------------------------
    Case("e001_unknown_directive", lambda ls: _encode(_after(ls, "VALIDITY", _directive("NOTES", "x")))),
    Case("e002_missing_validity_with_records", lambda ls: _encode(_drop(ls, "VALIDITY"))),
    Case("e002_empty_grammar", lambda ls: _encode(_set(ls, "GRAMMAR", ""))),
    Case(
        "e003_repeated_directive",
        lambda ls: _encode(_after(ls, "VALIDITY", _directive("TABLE", "conformance_case"))),
    ),
    # A BAD version, out of order: the file would be E010 if the order rule did not run first.
    Case(
        "e003_grammar_out_of_order",
        lambda ls: _encode(_after(_drop(ls, "GRAMMAR"), "DATASET", _directive("GRAMMAR", "2.0"))),
    ),
    Case("e004_wrong_field_count", lambda ls: _encode(_record(ls, 0, "1 1 1.5"))),
    Case("e004_blank_line_inside_records", lambda ls: _encode(_record(ls, 1, ""))),
    # C3 A9: valid UTF-8, so every UTF-8 tool in the chain still reads the directory, and still
    # outside the format's byte set.
    Case("e005_non_ascii_byte", lambda ls: _encode(_record(ls, 2, "6 12 3.5 0.3\xc3\xa9"))),
    Case("e005_control_byte", lambda ls: _encode(_record(ls, 2, "6 12 3.5 0.3\x01"))),
    Case("crlf_line_endings", _copied("crlf_line_endings.g4dat")),
    Case("comma_decimal", _copied("comma_decimal.g4dat")),
    Case("e007_valid_prefix_then_junk", lambda ls: _encode(_record(ls, 0, "1 1 1.5x 0.1"))),
    Case("e007_nan_in_integer_column", lambda ls: _encode(_record(ls, 0, "nan 1 1.5 0.1"))),
    Case("e007_integer_above_the_range", lambda ls: _encode(_record(ls, 2, "10000 12 3.5 0.3"))),
    Case("e007_double_plus_sign", lambda ls: _encode(_record(ls, 0, "1 1 ++1.5 0.1"))),
    Case("e008_duplicate_key", lambda ls: _encode(_record(ls, 1, "1 1 2.5 0.2"))),
    Case("e009_digest_mismatch", lambda ls: (_encode(ls), SIBLING_BYTES)),
    Case(
        "e010_unsupported_grammar_major",
        lambda ls: _encode(_set(ls, "GRAMMAR", "2.0")),
    ),
    Case("e011_content_after_end", lambda ls: _encode([*ls, "trailing"])),
    Case("e011_content_on_the_end_line", lambda ls: _encode([*ls[:-1], spec.END_MARKER + " x"])),
    Case("e012_records_but_no_end", lambda ls: _encode(ls[:-1])),
    # No records and no #END: the block never closes, so E012 replaces the missing-#VALIDITY E002.
    Case("e012_header_only_no_end_missing_validity", _header_only_no_end),
    Case("e012_empty_file", lambda _ls: b""),
    Case("e013_parity_without_sourcesha", lambda ls: _encode(_drop(ls, "SOURCESHA"))),
    Case(
        "e013_sourcesha_under_a_non_parity_profile",
        lambda ls: _encode(_set(ls, "PROFILE", "evaluated")),
    ),
    Case("e014_inf", lambda ls: _encode(_record(ls, 0, "1 1 inf 0.1"))),
    Case("e014_nan", lambda ls: _encode(_record(ls, 0, "1 1 nan 0.1"))),
    Case("e014_overflow_to_infinity", lambda ls: _encode(_record(ls, 0, "1 1 1e999 0.1"))),
    Case("e014_underflow_to_zero", lambda ls: _encode(_record(ls, 0, "1 1 1e-999 0.1"))),
    Case("e015_records_not_ascending", lambda ls: _encode(_record(_record(ls, 0, "6 12 3.5 0.3"), 2, "1 1 1.5 0.1"))),
    Case("e016_bad_profile", lambda ls: _encode(_set(ls, "PROFILE", "Parity!"))),
    Case("e016_bad_seam", lambda ls: _encode(_set(ls, "SEAM", "d9_not_a_seam"))),
    Case(
        "e016_sourcedigest_63_hex",
        lambda ls: _encode(_set(ls, "SOURCEDIGEST", hashlib.sha256(_SEED).hexdigest()[:-1])),
    ),
    Case(
        "e016_sourcedigest_upper_case",
        lambda ls: _encode(_set(ls, "SOURCEDIGEST", hashlib.sha256(_SEED).hexdigest().upper())),
    ),
    Case("e016_duplicate_column_name", lambda ls: _encode(_set(ls, "COLUMNS", "Z A value value"))),
    # -- the ordering rules and tie-breaks -----------------------------------------------------
    Case(
        "tie_non_ascii_preempts_a_bad_grammar",
        lambda ls: _encode(_record(_set(ls, "GRAMMAR", "2.0"), 2, "6 12 3.5 0.3\xc3\xa9")),
    ),
    Case(
        "tie_block_close_preempts_the_record_that_closed_it",
        lambda ls: _encode(_record(_drop(ls, "VALIDITY"), 0, "1 1 1.5")),
    ),
    Case(
        "tie_repeated_directive_preempts_a_missing_sourcesha",
        lambda ls: _encode(
            _after(_drop(ls, "SOURCESHA"), "VALIDITY", _directive("VALIDITY", "Z:listed A:listed"))
        ),
    ),
    Case(
        "tie_empty_grammar_preempts_a_wrong_field_count",
        lambda ls: _encode(_record(_set(ls, "GRAMMAR", ""), 0, "1 1 1.5")),
    ),
    Case(
        "tie_bad_columns_preempts_a_missing_sourcesha",
        lambda ls: _encode(_set(_drop(ls, "SOURCESHA"), "COLUMNS", "Z A value value")),
    ),
    Case(
        "tie_duplicate_key_preempts_unsorted",
        lambda ls: _encode(
            _record(_record(_record(ls, 0, "6 12 3.5 0.3"), 1, "1 1 1.5 0.1"), 2, "1 1 2.5 0.2")
        ),
    ),
    Case("stray_comment", _copied("stray_comment.g4dat")),
    # -- the accept cases: the format's boundaries, from the inside ----------------------------
    Case("ok_min_subnormal", lambda ls: _encode(_record(ls, 0, "1 1 4.9406564584124654e-324 0.1"))),
    Case("ok_zero_with_a_huge_negative_exponent", lambda ls: _encode(_record(ls, 0, "1 1 0e-999 0.1"))),
    Case("ok_leading_plus", lambda ls: _encode(_record(ls, 0, "1 1 +1.5 0.1"))),
    Case("ok_trailing_whitespace_on_a_record", lambda ls: _encode(_record(ls, 2, "6 12 3.5 0.3   "))),
    Case(
        "ok_digest_match",
        lambda ls: (
            _encode(_set(ls, "SOURCEDIGEST", provenance.source_digest(SIBLING_BYTES))),
            SIBLING_BYTES,
        ),
    ),
)


# --------------------------------------------------------------------------------------------
# build, write, audit
# --------------------------------------------------------------------------------------------


def build_members() -> dict[str, bytes]:
    """Every corpus file by name: the cases, their siblings, and ``expected.tsv``."""
    members: dict[str, bytes] = {}
    rows: list[str] = []
    for case in CASES:
        produced = case.build(list(TEMPLATE_LINES))
        payload, sibling = produced if isinstance(produced, tuple) else (produced, None)
        members[case.name + ".g4dat"] = payload
        if sibling is not None:
            members[case.name + ".prov.json"] = sibling
        code, line = reference_verdict(payload, sibling)
        rows.append(f"{case.name}.g4dat\t{code}\t{line}")
    # Sorted by file name and ASCII-encoded: the file is diffed by humans and read by a C++ test,
    # and neither should have to care what order the case table happens to be written in.
    members[EXPECTED_NAME] = ("\n".join(sorted(rows)) + "\n").encode("ascii")
    return members


def _write(members: dict[str, bytes], directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for name, payload in members.items():
        (directory / name).write_bytes(payload)  # binary: LF stays LF on every platform


def regenerate() -> None:
    members = build_members()
    _write(members, CORPUS)
    for name in sorted(members):
        print(f"wrote {(CORPUS / name).relative_to(ROOT).as_posix()}")
    print(f"{len(CASES)} case(s), {len(members)} file(s)")


def audit(directory: Path | None = None) -> None:
    """Rebuild into a temp dir and byte-compare against what is committed.

    Both directions are checked. A drifted file is the obvious failure; a file that exists on disk
    and in no case, or a case whose file was deleted, is the one that would otherwise let the corpus
    and the generator diverge without anything going red.
    """
    target = CORPUS if directory is None else directory
    members = build_members()
    committed = {path.name for path in target.iterdir() if path.is_file()}
    missing = sorted(set(members) - committed)
    extra = sorted(committed - set(members))
    if missing or extra:
        raise SystemExit(
            "g4dat conformance audit FAILED: the committed corpus and the generator disagree about "
            f"which files exist. Missing from disk: {missing or 'none'}. "
            f"On disk but not generated: {extra or 'none'}."
        )
    with tempfile.TemporaryDirectory() as scratch:
        fresh = Path(scratch)
        _write(members, fresh)
        drifted = sorted(
            name for name in members if not filecmp.cmp(fresh / name, target / name, shallow=False)
        )
    if drifted:
        raise SystemExit(
            "g4dat conformance audit FAILED: regenerated file(s) differ from the committed copy: "
            + ", ".join(drifted)
        )
    print(
        f"g4dat conformance audit OK: {len(CASES)} case(s), {len(members)} file(s) byte-identical "
        f"to the committed copy in {target.name}"
    )


def main(argv: list[str] | None = None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    if "--audit" in argv:
        audit()
    else:
        regenerate()


if __name__ == "__main__":
    main()
