"""Generate the example ``G4MuonicData`` dataset and its registration snippet.

    python scripts/generate_g4data.py           # regenerate data/g4/ and print the archive MD5
    python scripts/generate_g4data.py --audit   # rebuild into a temp dir and byte-compare

Stage 1 ships **no physics**. The rows below are format examples with round, obviously synthetic
numbers, and every Layer-2 field says so in words (``evaluation_method`` = "format example, not
evaluated physics", ``needs_verification`` = true, ``source_bibkey`` resolving to the format
specification itself). The dataset exists because the byte-diff audit needs a committed, regenerable
artifact to guard, and because a format with no example is a format nobody can check their reader
against. Nothing synthetic wears a physics label; D1 parity rows arrive in a later stage.

**Layer 2 is the source of truth**, with one honest exception. ``data/g4/example.prov.json`` is
hand-authored and everything Layer 1 declares about the dataset -- name, version, profile, seam, and
which ``(Z, A)`` rows exist -- is read out of it. The *numbers* cannot live there: Layer 2 carries
provenance, not values (``FORMAT_SPEC.md`` section 3). They are therefore declared here, and
:func:`build_table` fails if the two ever describe different row sets.

Audit wiring: ``example.g4dat`` and ``geant4_add_dataset.snippet`` are regenerated by this script and
both join ``make audit``'s ``git diff --exit-code`` list. The archive itself is **not committed** --
it is a build product whose determinism is proven by test rather than by a stored copy -- but its MD5
is written into the snippet, because a ``geant4_add_dataset`` block without a real ``MD5SUM`` is not
a usable block.
"""

from __future__ import annotations

import filecmp
import json
import sys
import tempfile
from pathlib import Path

import openmucf
from openmucf.g4 import emit, provenance, spec

ROOT = Path(__file__).resolve().parents[1]
G4DIR = ROOT / "data" / "g4"
LAYER2_PATH = G4DIR / "example.prov.json"
LAYER1_PATH = G4DIR / "example.g4dat"
SNIPPET_PATH = G4DIR / "geant4_add_dataset.snippet"

#: The environment variable a "mode 2" user exports (``FORMAT_SPEC.md`` section 5). Provisional.
DATASET_ENVVAR = "G4MUONICDATA"
TABLE_NAME = "format_example"
UNITS = "value=arbitrary unc=arbitrary"
COLUMNS = "Z A value unc"
VALIDITY = "Z:listed A:listed"

#: The example rows: round numbers, chosen so that no reader can mistake them for measurements.
#: Keys must match ``example.prov.json`` exactly -- see the module docstring.
EXAMPLE_RECORDS: tuple[tuple[int, int, float, float], ...] = (
    (1, 1, 1.0, 0.1),
    (6, 12, 2.0, 0.2),
    (29, 63, 3.0, 0.3),
)


def load_layer2() -> tuple[bytes, provenance.ProvDocument]:
    """Read the Layer-2 file as BYTES and check it is canonical.

    Binary, never text mode: the digest is taken over these exact bytes, and a text-mode read on
    Windows would silently hand back a different byte string than the file contains. The canonical
    check makes a hand edit that reflows the JSON a loud failure rather than a digest that quietly
    stops matching what a reader downloads.
    """
    raw = LAYER2_PATH.read_bytes()
    try:
        provenance.check_canonical_bytes(raw)
    except ValueError as exc:
        raise SystemExit(f"{LAYER2_PATH.relative_to(ROOT)}: {exc}") from None
    return raw, provenance.from_json_obj(json.loads(raw.decode("ascii")))


def build_table(raw: bytes, document: provenance.ProvDocument) -> spec.G4DatTable:
    """Render the Layer-1 table from the Layer-2 document plus the example numbers."""
    declared = {f"{z}-{a}" for z, a, *_ in EXAMPLE_RECORDS}
    if declared != set(document.rows):
        raise SystemExit(
            f"row sets disagree: {LAYER2_PATH.name} has {sorted(document.rows)}, this script has "
            f"{sorted(declared)}. Every Layer-1 record needs a Layer-2 row and vice versa."
        )
    directives = {
        "GRAMMAR": spec.GRAMMAR_VERSION,
        "DATASET": document.dataset,
        "VERSION": document.version,
        "PROFILE": document.profile,
        "SEAM": document.seam,
        "TABLE": TABLE_NAME,
        "GENERATOR": f"openmucf-g4 {openmucf.__version__}",
        "SOURCEDIGEST": provenance.source_digest(raw),
        "UNITS": UNITS,
        "COLUMNS": COLUMNS,
        "VALIDITY": VALIDITY,
    }
    table = spec.G4DatTable(directives=directives, records=EXAMPLE_RECORDS)
    spec.validate(table)
    provenance.check_against_table(table, document)
    # A wiring assertion, not an integrity check: the digest three lines up was just derived from
    # `raw`, so this can only fire if a caller hands build_table() two different byte strings. The
    # integrity check that has teeth is in audit(), against the two COMMITTED files.
    provenance.check_source_digest(table, raw)
    return table


def build_artifacts() -> tuple[dict[Path, bytes], bytes]:
    """The committed artifacts keyed by path, plus the archive they describe (not committed)."""
    raw, document = load_layer2()
    table = build_table(raw, document)
    layer1 = spec.render(table).encode("ascii")
    archive = emit.build_tarball({LAYER1_PATH.name: layer1, LAYER2_PATH.name: raw})
    snippet = emit.add_dataset_snippet(
        name=document.dataset,
        version=document.version,
        filename=document.dataset,
        envvar=DATASET_ENVVAR,
        md5=emit.tarball_md5(archive),
    )
    return {LAYER1_PATH: layer1, SNIPPET_PATH: snippet.encode("ascii")}, archive


def _write(artifacts: dict[Path, bytes], directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for path, payload in artifacts.items():
        (directory / path.name).write_bytes(payload)  # binary: LF stays LF on every platform


def regenerate() -> None:
    artifacts, archive = build_artifacts()
    _write(artifacts, G4DIR)
    for path in artifacts:
        print(f"wrote {path.relative_to(ROOT).as_posix()}")
    print(
        f"archive {LAYER1_PATH.stem}.{emit.ARCHIVE_EXTENSION} (not committed): "
        f"{len(archive)} bytes, md5={emit.tarball_md5(archive)}"
    )


def audit() -> None:
    """Rebuild into a temp dir and byte-compare against what is committed."""
    # The cross-layer invariant on the COMMITTED pair, checked FIRST -- both files read from disk,
    # neither derived from the other. It has to run before the regenerate-and-compare below or it can
    # never fire: Layer 1 embeds sha256(Layer 2), so any drift between the two also changes the
    # regenerated bytes, and the byte-diff would report "an artifact differs" while this line, which
    # names both layers and gives the consumer-facing code, never executed.
    try:
        committed = spec.parse(LAYER1_PATH.read_bytes().decode("ascii"))
        provenance.check_source_digest(committed, LAYER2_PATH.read_bytes())
    except spec.G4DatFormatError as exc:
        # A coded, located message and a clean exit, like every other failure here -- not the stack
        # trace a bare raise would print at whoever is running `make audit`.
        raise SystemExit(f"g4data audit FAILED: the committed dataset does not validate: {exc}") from None

    artifacts, archive = build_artifacts()
    with tempfile.TemporaryDirectory() as scratch:
        fresh = Path(scratch)
        _write(artifacts, fresh)
        drifted = [
            path.name
            for path in artifacts
            if not (path.exists() and filecmp.cmp(fresh / path.name, path, shallow=False))
        ]
    if drifted:
        raise SystemExit(
            "g4data audit FAILED: regenerated artifact(s) differ from the committed copy: "
            + ", ".join(sorted(drifted))
        )
    # Determinism is a property of the builder, not of one run: build again and compare.
    if emit.build_tarball(
        {LAYER1_PATH.name: artifacts[LAYER1_PATH], LAYER2_PATH.name: LAYER2_PATH.read_bytes()}
    ) != archive:
        raise SystemExit("g4data audit FAILED: two archive builds in one process differ")
    print(
        f"g4data audit OK: {len(artifacts)} artifact(s) byte-identical to the committed copy; "
        f"committed cross-layer digest verified (E009 clean); "
        f"archive reproducible in-process (md5={emit.tarball_md5(archive)})"
    )


def main(argv: list[str] | None = None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    if "--audit" in argv:
        audit()
    else:
        regenerate()


if __name__ == "__main__":
    main()
